services:
  keycloak:
    container_name: keycloak26.0.7
    image: quay.io/keycloak/keycloak:26.0.7
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "7080:8080"
    command:
      - "start-dev"
    networks:
      - app-network
  cache:
    image: redis:7.4.1-alpine3.20
    container_name: redis7
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes:
      - cache:/data
    networks:
      - app-network
volumes:
  cache:
    driver: local
networks:
  app-network:
    driver: bridge
